config:
  useHttps: true
  fqdn: "chat.example.com"
  NEXTAUTH_SECRET: "mNj1Hm5n6wXjat7MjZT6uWG9SH6AKDWGyT+4iDejZQk="
  LLM_PROVIDER_CONFIG_LOCK: false
  SSO_CONFIG_LOCK: false
  ENABLE_SIGNUP: true
  ENABLE_TOOLS: false

database:
  type: "sqlite" # Options: "sqlite", "postgres"

  postgres: # If type is postgres you need to se the following paramaters to connect to an external postgres database
    host: "postgres.example.com"
    port: 5432
    dbName: "logicle"
    user: "admin"
    password: "securepassword"

ingress:
  enabled: true
  ingressClass: "nginx"

storage:
  enabled: true

  files:
    persistentVolumeClaim:
      existingClaim: ""
      storageClass: manual
      size: 1Gi
      accessMode: ReadWriteOnce
  
  sqlite:
    persistentVolumeClaim:
      existingClaim: ""
      storageClass: manual
      size: 1Gi
      accessMode: ReadWriteOnce