{{- $sqlite := .Values.storage.sqlite.persistentVolumeClaim -}}
{{- $files := .Values.storage.files.persistentVolumeClaim }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "logicle.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logicle
  template:
    metadata:
      labels:
        app: logicle
    spec:
      containers:
      - name: app
        image: "ghcr.io/logicleai/logicle:{{ .Chart.AppVersion }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: {{ include "logicle.fullname" . }}
        - secretRef:
            name: {{ include "logicle.fullname" . }}
{{- if .Values.storage.enabled }}
        volumeMounts:
        {{- if eq .Values.database.type "sqlite" }}
        - name: sqlite-data
          mountPath: /data/sqlite
        {{- end }}
        - name: uploaded-files-data
          mountPath: /data/files
{{- end }}
{{- if .Values.storage.enabled }}
      volumes:
      {{- if eq .Values.database.type "sqlite" }}
      - name: sqlite-data
        {{- if $sqlite.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ $sqlite.existingClaim }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "logicle.fullname" . }}-sqlite
        {{- end }}
      {{- end }}
      - name: uploaded-files-data
        {{- if $files.existingClaim }}
        persistentVolumeClaim:
          claimName: {{ $files.existingClaim }}
        {{- else }}
        persistentVolumeClaim:
          claimName: {{ include "logicle.fullname" . }}-files
        {{- end }}
{{- end }}