apiVersion: v1
kind: Secret
metadata:
  name: {{ include "logicle.fullname" . }}
type: Opaque
stringData:
  NEXTAUTH_SECRET: {{ .Values.config.NEXTAUTH_SECRET | quote }}
{{- if eq .Values.database.type "sqlite" }}
  DATABASE_URL: "file:///data/sqlite/logicle.sqlite"
{{- else if eq .Values.database.type "postgres" }}
  DATABASE_URL: "postgresql://{{ .Values.database.postgres.user }}:{{ .Values.database.postgres.password }}@{{ .Values.database.postgres.host }}:{{ .Values.database.postgres.port }}/{{ .Values.database.postgres.dbName }}"
{{- end }}