apiVersion: v1
kind: Service
metadata:
  name: {{ include "logicle.fullname" . }}
spec:
  selector:
    app: logicle
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080